language: elixir
elixir:
- 1.3
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database podcasts_api_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: qhHx8RXnyFYTcIiNyPGCDx2+TZ8nnfN7rr2Ct3p1CCl1GL7W0lE4Em6dsAei7gdfStzmY8hKtkSsOyso3ElajMeT1zYaI8PR/fdHRXum9FhaJwQzazmSdZEF1WRfvjmPkfaZMlFRkK5EfiljwqqK9FNnGOt+CTVvY09/qGgSX1DRCIKpzFTSK0xpwqic0qQjk93G8Ri7VYP5Fo/DU6rW7ez3DqJEikkRSVxN1wR+tjTD3kD4SkLrp893p1GK5h1pmxmBzyGBfmEvkryaYURnxgfKcLsvas3TdaTL1jekN/pKRMNjh3Ol1qFjO1dHHKho7R8VihhoZs99yHyfyfaM2PyyqRDTvnBB+zM+DJQOkS8zaQ/UV29APO/Nrg1zf583UvfRBxcEIuAFNXf9PBDCULNeTXyg78yXHO3eZCfkJdJ+sO0QlqR8rFqo7wugETU9nkmtpl965gP5mDVtTJ6l7mXGW/MTMlG2/VcnUjlRpeNPkH/72hS0EHGjbVRWQ6+fgVTmlAWw+EurIVnhRWKyKlUs+Isq01w9I3von280exz3tWBz8/OUl25F9dTHBWk4f1COFikorhTa139kFs+qQU8D+OBOs7Mvgdo2SvA/HwwNehefkOldxfpDNXVuzbOTuLBGiynb7LfYlsSyw2nIO/y5d1oGy8HBl8rnPgkwxa0=
  app: salty-sea-35575
  on:
    repo: tkloht/podcasts_api
